### ISSUE TITLE
Cloaking issues

### ISSUE THREAD

**Issue by ShaleCoders** [CustomIRCd/sIRCd#19]
When hostname contains a full stop it'll only cloak to that part. This can be a security threat and needs fixing

Example: my hostname is with.no.rdns.shalecoders.net and only the with gets mangled

**Comment by TwinUsers** [comment]
@ShaleCoders I have been looking into this already and hopefully I'll have a solution ready in the morning 🎉

I'll introduce my previous cloaking that was removed as we made m_cloaking a module rather than an extension. It had a configurable option in the ircd.conf however it would be better if you just read the network_name from the ServerInfo part of the config.

I'll try my best, but can't promise it'll be done tomorrow

**Comment by TwinUsers** [comment]
after making changes, we've reverted back to original cloaking. I'm going to look into the original source deeper and get a better solution in a feature release

Thanks

**Comment by CustomIRCd** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Release 1.1.3](https://trello.com/c/mWED4UAV/1-release-113)
